/* Reopen and read back an applied reference-stack property plan. Read-only. */
(function () {
    app.exitAfterLaunchAndEval = true;

    function readText(path){var f=new File(path);f.encoding="UTF-8";if(!f.open("r"))throw new Error("Cannot read: "+path);var v=f.read();f.close();return v;}
    function quote(value){return '"'+String(value).replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/\t/g,"\\t")+'"';}
    function json(value){if(value===null||value===undefined)return"null";if(typeof value==="string")return quote(value);if(typeof value==="number")return isFinite(value)?String(value):"null";if(typeof value==="boolean")return value?"true":"false";if(value instanceof Array){var a=[],i;for(i=0;i<value.length;i++)a.push(json(value[i]));return"["+a.join(",")+"]";}var p=[],k;for(k in value)if(value.hasOwnProperty(k))p.push(quote(k)+":"+json(value[k]));return"{"+p.join(",")+"}";}
    function writeJson(path,value){var f=new File(path);f.encoding="UTF-8";if(!f.open("w"))throw new Error("Cannot write: "+path);f.write(json(value));f.close();}
    function normalize(path){return String(path).replace(/\\/g,"/").toLowerCase();}
    function cloneValue(value){if(value instanceof Array){var a=[],i;for(i=0;i<value.length;i++)a.push(Number(value[i]));return a;}return Number(value);}
    function valueDistance(a,b){if(a instanceof Array&&b instanceof Array){if(a.length!==b.length)return 1e12;var d=0,i;for(i=0;i<a.length;i++)d=Math.max(d,Math.abs(Number(a[i])-Number(b[i])));return d;}return Math.abs(Number(a)-Number(b));}
    function findItemById(id){var i,item;for(i=1;i<=app.project.numItems;i++){item=app.project.item(i);if(item&&Number(item.id)===Number(id))return item;}return null;}
    function findComp(id){var item=findItemById(id);return item&&(item instanceof CompItem)?item:null;}
    function sourceName(layer){try{return layer.source?String(layer.source.name):"";}catch(ignore){return"";}}
    function validateLayer(update){var comp=findComp(Number(update.compId));if(!comp)throw new Error("Comp not found: "+update.compId);var layer=comp.layer(Number(update.layerIndex));if(!layer)throw new Error("Layer not found: "+update.compId+"/"+update.layerIndex);if(String(layer.name)!==String(update.layerName))throw new Error("Layer name mismatch");if(update.sourceId!==null&&update.sourceId!==undefined){if(!layer.source||Number(layer.source.id)!==Number(update.sourceId))throw new Error("Layer source mismatch");}return layer;}
    function transformProperty(layer,matchName){if(matchName!=="ADBE Position"&&matchName!=="ADBE Scale")throw new Error("Unsupported property: "+matchName);var t=layer.property("ADBE Transform Group");if(!t)throw new Error("Missing transform group");var p=t.property(matchName);if(!p)throw new Error("Missing property: "+matchName);return p;}
    function validateDependencyLocks(locks){var states=[],errors=[],i,lock,item,file,state;for(i=0;i<locks.length;i++){lock=locks[i];item=findItemById(Number(lock.itemId));file=null;if(!item||!(item instanceof FootageItem)){errors.push({itemId:lock.itemId,error:"missing FootageItem"});continue;}try{file=item.file;}catch(ignore){}state={itemId:Number(item.id),itemName:String(item.name),path:file?String(file.fsName):null,exists:!!(file&&file.exists),width:Number(item.width),height:Number(item.height)};if(lock.itemName!==undefined&&String(lock.itemName)!==state.itemName)errors.push({itemId:lock.itemId,error:"item name mismatch",actual:state.itemName});if(lock.path!==undefined&&(!file||normalize(file.fsName)!==normalize(lock.path)))errors.push({itemId:lock.itemId,error:"path mismatch",actual:state.path});if(lock.width!==undefined&&Number(lock.width)!==state.width)errors.push({itemId:lock.itemId,error:"width mismatch",actual:state.width});if(lock.height!==undefined&&Number(lock.height)!==state.height)errors.push({itemId:lock.itemId,error:"height mismatch",actual:state.height});if(!state.exists)errors.push({itemId:lock.itemId,error:"file missing",actual:state.path});states.push(state);}return{states:states,errors:errors};}
    function validateDisabledLocks(locks){var states=[],errors=[],i,lock,comp,layer,state,expected;for(i=0;i<locks.length;i++){lock=locks[i];comp=findComp(Number(lock.compId));if(!comp){errors.push({compId:lock.compId,error:"comp missing"});continue;}layer=comp.layer(Number(lock.layerIndex));if(!layer){errors.push({compId:lock.compId,layerIndex:lock.layerIndex,error:"layer missing"});continue;}expected=lock.mustBeEnabled===true;state={compId:Number(comp.id),layerIndex:Number(layer.index),layerName:String(layer.name),sourceName:sourceName(layer),enabled:!!layer.enabled,expectedEnabled:expected};if(String(layer.name)!==String(lock.layerName))errors.push({compId:lock.compId,layerIndex:lock.layerIndex,error:"layer name mismatch",actual:String(layer.name)});if(lock.sourceName!==undefined&&String(lock.sourceName)!==state.sourceName)errors.push({compId:lock.compId,layerIndex:lock.layerIndex,error:"source name mismatch",actual:state.sourceName});if(state.enabled!==expected)errors.push({compId:lock.compId,layerIndex:lock.layerIndex,error:"enabled-state mismatch",actual:state.enabled,expected:expected});states.push(state);}return{states:states,errors:errors};}
    function missingFootage(scope){var rows=[],i,item,file;for(i=1;i<=app.project.numItems;i++){item=app.project.item(i);if(!item||!(item instanceof FootageItem)||!routeAllowsFootage(scope,Number(item.id)))continue;file=null;try{file=item.file;}catch(ignore){}if(file&&!file.exists)rows.push({itemId:Number(item.id),itemName:String(item.name),path:String(file.fsName)});}return rows;}
    function scanGroup(group,path,errors){if(!group||!group.numProperties)return;var i,p;for(i=1;i<=group.numProperties;i++){p=group.property(i);if(!p)continue;if(p.propertyType===PropertyType.PROPERTY){try{if(p.expressionEnabled&&p.expressionError)errors.push({path:path+"/"+p.name,error:String(p.expressionError)});}catch(ignore){}}else scanGroup(p,path+"/"+p.name,errors);}}
    function expressionErrors(scope){var rows=[],i,item,j;for(i=1;i<=app.project.numItems;i++){item=app.project.item(i);if(!item||!(item instanceof CompItem)||!routeAllowsComp(scope,Number(item.id)))continue;for(j=1;j<=item.numLayers;j++)scanGroup(item.layer(j),String(item.name)+"/"+String(item.layer(j).name),rows);}return rows;}
    function watermarkLayers(scope){var rows=[],i,item,j,layer,s,hay;for(i=1;i<=app.project.numItems;i++){item=app.project.item(i);if(!item||!(item instanceof CompItem)||!routeAllowsComp(scope,Number(item.id)))continue;for(j=1;j<=item.numLayers;j++){layer=item.layer(j);s=sourceName(layer);hay=String(layer.name)+" "+s;if(/watermark|水印/i.test(hay))rows.push({compId:Number(item.id),compName:String(item.name),layerIndex:Number(layer.index),layerName:String(layer.name),sourceName:s,enabled:!!layer.enabled});}}return rows;}
    function containsNumber(values,target){var i;if(!(values instanceof Array))return false;for(i=0;i<values.length;i++)if(Number(values[i])===Number(target))return true;return false;}
    function routeAllowsComp(scope,compId){return !scope||containsNumber(scope.compIds,compId);}
    function routeAllowsFootage(scope,itemId){return !scope||containsNumber(scope.routeCriticalFootageItemIds,itemId);}
    function missingKey(row){return String(row.itemId)+"|"+normalize(row.path||"");}
    function expressionKey(row){return String(row.path||"")+"|"+String(row.error||"");}
    function watermarkKey(row){return String(row.compId)+"/"+String(row.layerIndex)+"|"+String(row.layerName||"")+"|"+String(row.sourceName||"");}
    function newIssues(rows,accepted,keyFunction){var allowed={},result=[],i,key;accepted=accepted||[];for(i=0;i<accepted.length;i++)allowed[String(accepted[i])]=true;for(i=0;i<rows.length;i++){key=keyFunction(rows[i]);rows[i].issueKey=key;if(!allowed[key])result.push(rows[i]);}return result;}
    function readbackUpdates(updates){var errors=[],i,u,layer,p,k,key,actual,tolerance;for(i=0;i<updates.length;i++){u=updates[i];try{layer=validateLayer(u);p=transformProperty(layer,String(u.propertyMatchName));}catch(error){errors.push({updateIndex:i,error:String(error)});continue;}if(Number(p.numKeys)!==Number(u.expectedNumKeys)){errors.push({updateIndex:i,error:"key count mismatch",actual:Number(p.numKeys),expected:Number(u.expectedNumKeys)});continue;}if(u.keys instanceof Array){for(k=0;k<u.keys.length;k++){key=u.keys[k];actual=cloneValue(p.keyValue(Number(key.keyNumber)));tolerance=key.tolerance===undefined?0.1:Number(key.tolerance);if(valueDistance(actual,key.newValue)>tolerance)errors.push({updateIndex:i,keyNumber:Number(key.keyNumber),error:"new key value mismatch",actual:actual,expected:key.newValue});}}else{actual=cloneValue(p.value);tolerance=u.tolerance===undefined?0.1:Number(u.tolerance);if(valueDistance(actual,u.newValue)>tolerance)errors.push({updateIndex:i,error:"new static value mismatch",actual:actual,expected:u.newValue});}}return errors;}

    var resultPath=null;
    try{
        var jobPath=$.getenv("AE_STACK_V2_JOB");if(!jobPath)throw new Error("AE_STACK_V2_JOB is not set");
        var job=eval("("+readText(jobPath)+")");resultPath=job.resultPath;
        var library=normalize(Folder(job.libraryPath).fsName),staging=library+"/.staging/",project=normalize(File(job.projectPath).fsName);
        if(project.indexOf(staging)!==0)throw new Error("Verification project is outside library staging");
        var plan=eval("("+readText(job.planPath)+")");
        if(!plan.safety||plan.safety.originalAepEdited!==false||plan.safety.referenceSourceAepUsed!==false||plan.safety.referenceSourceGeometryUsed!==false)throw new Error("Property plan safety flags failed");
        app.open(new File(job.projectPath));
        var scope=plan.routeScope||{},baseline=plan.qaBaseline||{},updates=plan.propertyUpdates||[],readback=readbackUpdates(updates),dependencies=validateDependencyLocks(plan.dependencyLocks||[]),disabled=validateDisabledLocks(plan.requiredDisabledLayers||[]),missing=missingFootage(scope),expressions=expressionErrors(scope),watermarks=watermarkLayers(scope),enabledWatermarks=[],newMissing,newExpressions,newWatermarks,i;
        for(i=0;i<watermarks.length;i++)if(watermarks[i].enabled)enabledWatermarks.push(watermarks[i]);
        newMissing=newIssues(missing,baseline.acceptedMissingKeys||baseline.acceptedMissingFootageKeys||[],missingKey);
        newExpressions=newIssues(expressions,baseline.acceptedExpressionErrorKeys||[],expressionKey);
        newWatermarks=newIssues(enabledWatermarks,baseline.acceptedEnabledWatermarkKeys||[],watermarkKey);
        var ok=readback.length===0&&dependencies.errors.length===0&&disabled.errors.length===0&&newMissing.length===0&&newExpressions.length===0&&newWatermarks.length===0;
        writeJson(resultPath,{schemaVersion:2,artifactType:"apply-readback",ok:ok,mode:"read-only-reference-stack-property-verification-v2",projectPath:File(job.projectPath).fsName,propertyUpdateCount:updates.length,readbackErrors:readback,dependencyStates:dependencies.states,dependencyErrors:dependencies.errors,disabledLayerStates:disabled.states,disabledLayerErrors:disabled.errors,routeScope:scope,qaBaseline:baseline,routeCriticalMissing:missing,newRouteCriticalMissing:newMissing,routeExpressionErrors:expressions,newRouteExpressionErrors:newExpressions,enabledWatermarks:enabledWatermarks,newEnabledWatermarks:newWatermarks,referenceSourceAepUsed:false,referenceSourceGeometryUsed:false});
        try{app.project.close(CloseOptions.DO_NOT_SAVE_CHANGES);}catch(ignoreClose){}try{app.quit();}catch(ignoreQuit){}
    }catch(error){if(resultPath){try{writeJson(resultPath,{ok:false,error:String(error),line:error.line||null});}catch(ignoreWrite){}}try{app.project.close(CloseOptions.DO_NOT_SAVE_CHANGES);}catch(ignoreCloseOnError){}try{app.quit();}catch(ignoreQuitOnError){}}
}());
